### ISSUE TITLE
Add support for phir `"qparallel"` blocks

### ISSUE THREAD

**Issue by qartik** [PECOS-packages/PECOS#26]
https://github.com/CQCL/pytket-phir/pull/53 adds support for generating `"qparallel"` blocks. The corresponding support in PECOS is needed. Currently, it fails with:
```
❯ phirc tests/data/qasm/n10_test.qasm
Processing tests/data/qasm/n10_test.qasm
Traceback (most recent call last):
  File "pytket-phir/.venv/bin/phirc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "pytket-phir/.venv/lib/python3.11/site-packages/pytket/phir/cli.py", line 67, in main
    HybridEngine(qsim="state-vector").run(program=phir, shots=10)
  File "pytket-phir/.venv/lib/python3.11/site-packages/pecos/engines/hybrid_engine.py", line 158, in run
    self.initialize_sim_components(program, foreign_object)
  File "pytket-phir/.venv/lib/python3.11/site-packages/pecos/engines/hybrid_engine.py", line 99, in initialize_sim_components
    num_qubits = self.cinterp.init(program, foreign_object)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pytket-phir/.venv/lib/python3.11/site-packages/pecos/classical_interpreters/phir_classical_interpreter.py", line 88, in init
    self.program = PyPMIR.from_phir(self.program)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pytket-phir/.venv/lib/python3.11/site-packages/pecos/reps/pypmir/pypmir.py", line 194, in from_phir
    instr = cls.handle_op(o, p)
            ^^^^^^^^^^^^^^^^^^^
  File "pytket-phir/.venv/lib/python3.11/site-packages/pecos/reps/pypmir/pypmir.py", line 71, in handle_op
    raise Exception(msg)
Exception: Block not recognized: {'block': 'qparallel', 'ops': [{'qop': 'RZ', 'angles': [[1.5], 'pi'], 'args': [['q', 0], ['q', 2], ['q', 4], ['q', 9]]}, {'qop': 'RZ', 'angles': [[0.5], 'pi'], 'args': [['q', 1], ['q', 3], ['q', 10]]}]}
```

**Comment by ciaranra** [comment]
PR #33 solved this issue.
